name: Build and test Go
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Check out source code
        uses: actions/checkout@v4

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make build

      - name: Unit Tests
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make test